# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Amit Tomar'
tagline:             'At the cusp of Arts and Computer Science..'
description:         'Info about Amit Tomar and his Blog'
#url:                'http://127.0.0.1:4000'
url:		             'https://amit-tomar.github.io'
baseurl:             ''
github_username:     'AmitTomar'
highlighter: 		      rouge
#paginate_path: 		 '/postCollection/page:num'
#paginate:			 2
# About/contact
author:
  name:              Amit Tomar
  url:               'https://amit-tomar.github.io'
  email:             amit.tomar@iiitb.org

# Custom vars
version:             1.0.0
